### ISSUE TITLE
Question regarding normalizing scale depth

### ISSUE THREAD

**Issue by YuxuanSnow** [mbaradad/depth_prompt#2]
Hi,

i notice that in the data loading process, you normalize each depth with the mean value (https://github.com/mbaradad/depth_prompt/blob/main/depth_metrics_and_losses.py#L118). I wonder why you multiply this by 5 finally. Besides, does this number affect the result?

Thans for reply!

**Comment by mbaradad** [comment]
With the losses used, the normalizing does not affect the algorithm (as losses are scale invariant). Despite this, we normalize to reasonable ranges to avoid precision errors/nan's.
